app_admin_etl_execution:
    type: sylius.resource
    prefix: /admin
    resource: |
        alias: app.etl_execution
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_admin_etl_execution
        permission: true
        vars:
            all:
                subheader: app.ui.etl_execution.grid.title
                header: app.ui.etl_execution.grid.title

app_admin_etl_execution_show:
    path: admin/etl-executions/{id}
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::showAction'
        _sylius:
            section: admin
            permission: true

app_admin_etl_execution_dashboard:
    path: admin/etl-execution-dashboard
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\DashboardController::indexAction'
        _sylius:
            section: admin
            permission: true
    
app_admin_etl_execution_execute:
    path: admin/etl-execution-execute/{name}/{definition?}/{inputData?}/{inputOptions?}
    methods: [ GET ]
    defaults:
        _controller: 'Oliverde8\PhpEtlSyliusAdminBundle\Controller\EtlController::ExecuteAction'
        _sylius:
            section: admin
            permission: true
