sylius_grid:
    templates:
        filter:
            etl_execution_name: "@SyliusUi/Grid/Filter/select.html.twig"
        action:
            executeEtl: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/actions/execute_etl.html.twig"
    grids: 
        app_admin_etl_execution:
            driver:
                name: doctrine/orm
                options:
                    class: Oliverde8\PhpEtlSyliusAdminBundle\Entity\Etl\EtlExecution
                    repository:
                        method: createAdminGridQueryBuilder
            fields:
                id:
                    type: string
                    label: "ID"
                name:
                    type: string
                    label: app.ui.etl_execution.grid.name
                createTime:
                    type: datetime
                    label: app.ui.etl_execution.grid.createTime
                startTime:
                    type: datetime
                    label: app.ui.etl_execution.grid.startTime
                endTime:
                    type: datetime
                    label: app.ui.etl_execution.grid.endTime
                status:
                    label: app.ui.etl_execution.grid.status
                    type: twig
                    options:
                        template: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/fields/etl_status.html.twig"
            
            filters:
                name:
                    type: etl_execution_name
                    label: app.ui.etl_execution.grid.name
                status:
                    type: select
                    label: app.ui.etl_execution.grid.status
                    form_options:
                        choices:
                            "app.ui.etl_execution.statuses.success": "success"
                            "app.ui.etl_execution.statuses.running": "running"
                            "app.ui.etl_execution.statuses.failure": "failure"
                            "app.ui.etl_execution.statuses.waiting": "waiting"
                            "app.ui.etl_execution.statuses.queued": "queued"
                startTime:
                    type: date
                    label: app.ui.etl_execution.grid.startTime
                endTime:
                    type: date
                    label: app.ui.etl_execution.grid.endTime
                createTime:
                    type: date
                    label: app.ui.etl_execution.grid.createTime
            
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                        enabled: true
                        label: ""
                    executeEtl:
                        type: executeEtl
                        label: app.ui.etl_execution.grid.execute
                        options:
                            link:
                                route: app_admin_etl_execution_execute
                                parameters:
                                    id: resource.id
                                data:
                                    status: resource.status
