sylius_grid:
    templates:
        filter:
            etl_execution_name: "@SyliusUi/Grid/Filter/select.html.twig"
    grids: 
        app_admin_etl_execution:
            driver:
                name: doctrine/orm
                options:
                    class: Oliverde8\PhpEtlSyliusAdminBundle\Entity\Etl\EtlExecution
                    repository:
                        method: createAdminGridQueryBuilder
            fields:
                id:
                    type: string
                    label: "ID"
                name:
                    type: twig
                    label: app.ui.etl_execution.name
                    options:
                        template: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/fields/etl_names.html.twig"
                startTime:
                    type: datetime
                    label: app.ui.etl_execution.startTime
                endTime:
                    type: datetime
                    label: app.ui.etl_execution.endTime
                status:
                    label: app.ui.etl_execution.status
                    type: twig
                    options:
                        template: "@Oliverde8PhpEtlSyliusAdmin/etl/grid/fields/etl_status.html.twig"
            
            filters:
                name:
                    type: etl_execution_name
                    label: app.ui.etl_execution.name
                status:
                    type: select
                    label: app.ui.etl_execution.status
                    form_options:
                        choices:
                            "app.ui.etl_execution.statuses.success": "success"
                            "app.ui.etl_execution.statuses.running": "running"
                            "app.ui.etl_execution.statuses.failure": "failure"
                startTime:
                    type: date
                    label: app.ui.etl_execution.startTime
                endTime:
                    type: date
                    label: app.ui.etl_execution.endTime
            
            actions:
                item:
                    show:
                        type: show
                        enabled: true
                        label: ""
